"""Test Case: Login
Scenario: SC-1 | Test Case ID: TC-1
Generated by Test Case Generation Platform.
"""
import pytest
from playwright.sync_api import Page, expect
from modules.core.pages.home_page import HomePage

@pytest.mark.regression
def test_login(page: Page, default_credentials: dict) -> None:
    """Login."""
    home_page = HomePage(page)

    # Step 1: Navigate to base application
    home_page.navigate()
    home_page.assert_loaded()

    # Step 1: Open
