"""Test Case: Unsupported carousel
Scenario: SC-1 | Test Case ID: TC-2
Generated by Test Case Generation Platform.
"""
import pytest
from playwright.sync_api import Page, expect
from modules.core.pages.home_page import HomePage

@pytest.mark.regression
def test_unsupported_carousel(page: Page, default_credentials: dict) -> None:
    """Unsupported carousel."""
    home_page = HomePage(page)

    # Step 1: Navigate to base application
    home_page.navigate()
    home_page.assert_loaded()

    # Step 1: Select carousel mode
